#%RAML 1.0

# Objective: This RAML illustrates an example of how you define multiple default media types
# Expected result: no error message

# tags: default media type, media type

title: New API
mediaType: [ application/json, application/xml ]

description: This RAML illustrates an array of default media types.
