#%RAML 1.0

# Objective: This RAML illustrates an example of how you don't have to define an array when you use a single default media type.
# Expected result: no error message

# tags: default media type, media type

title: New API
mediaType: application/json

description: This RAML illustrates a single value default media type.
