#%RAML 1.0

# Objective: This RAML illustrates an example of how to define a boolean type.
# Expected result: no error message

# tags: type, boolean

title: Boolean Type

types:
  IsMarried:
    type: boolean
